runtime: nodejs20

# App Engine configuration for FCM Push Notification Server

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080
  GAE_APPLICATION: "true"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Network configuration
network:
  session_affinity: false

# Resource limits
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
