version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: project-app:latest
    container_name: project_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    networks:
      - project_network

  nginx:
    image: nginx:alpine
    container_name: project_nginx
    restart: unless-stopped
    ports:
      - "8007:80"
    volumes:
      - .:/var/www
      - /var/www/vendor
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - project_network

networks:
  project_network:
    driver: bridge 