name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Pull Request
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    
    - name: Run unit tests
      run: |
        python run_unit_tests.py
    
    - name: Run integration tests  
      run: |
        python test_integration.py
    
    - name: Code quality checks
      run: |
        pip install flake8 black
        echo "Running code quality checks..."
        black --check . || echo "Code formatting issues found"
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    
    - name: Security scan
      run: |
        pip install bandit safety
        echo "Running security checks..."
        bandit -r modules/ || echo "Security issues found"
        safety check || echo "Dependency vulnerabilities found"
